// --- Dữ liệu giả lập ---
// Trong ứng dụng thực tế, dữ liệu này sẽ được lấy từ API.
export const mockProducts = [
  {
    id: "SP001",
    name: "Táo Envy New Zealand",
    img: "https://via.placeholder.com/80x80.png?text=Táo+Envy",
    category: "Táo & Lê",
    price: 250000,
    stock: 120,
    status: "Còn hàng",
  },
  {
    id: "SP002",
    name: "Cam Vàng Navel Úc",
    img: "https://via.placeholder.com/80x80.png?text=Cam+Navel",
    category: "Họ Cam Quýt",
    price: 180000,
    stock: 80,
    status: "Còn hàng",
    description:
      "Cam vàng Navel Úc có vị ngọt đậm, mọng nước, vỏ mỏng và dễ bóc. Thích hợp để ăn tươi hoặc vắt nước.",
  },
  {
    id: "SP003",
    name: "Dâu Tây Hàn Quốc",
    img: "https://via.placeholder.com/80x80.png?text=Dâu+Tây",
    category: "Quả Mọng",
    price: 450000,
    stock: 8,
    status: "Sắp hết hàng",
    description:
      "Dâu tây Hàn Quốc quả to, đỏ mọng, hương thơm nồng nàn và vị ngọt thanh. Là một trong những loại dâu tây ngon nhất thế giới.",
  },
  {
    id: "SP004",
    name: "Nho Xanh không hạt Mỹ",
    img: "https://via.placeholder.com/80x80.png?text=Nho+Xanh",
    category: "Quả Mọng",
    price: 320000,
    stock: 50,
    status: "Còn hàng",
  },
  {
    id: "SP005",
    name: "Xoài Cát Hòa Lộc",
    img: "https://via.placeholder.com/80x80.png?text=Xoài+Cát",
    category: "Trái cây nhiệt đới",
    price: 90000,
    stock: 0,
    status: "Hết hàng",
  },
  {
    id: "SP006",
    name: "Kiwi Vàng New Zealand",
    img: "https://via.placeholder.com/80x80.png?text=Kiwi",
    category: "Trái cây nhiệt đới",
    price: 150000,
    stock: 75,
    status: "Còn hàng",
  },
  {
    id: "SP007",
    name: "Lê Nam Phi",
    img: "https://via.placeholder.com/80x80.png?text=Lê+Nam+Phi",
    category: "Táo & Lê",
    price: 110000,
    stock: 90,
    status: "Còn hàng",
  },
  {
    id: "SP008",
    name: "Việt Quất Chile",
    img: "https://via.placeholder.com/80x80.png?text=Việt+Quất",
    category: "Quả Mọng",
    price: 380000,
    stock: 30,
    status: "Còn hàng",
  },
  {
    id: "SP009",
    name: "Bưởi Da Xanh",
    img: "https://via.placeholder.com/80x80.png?text=Bưởi",
    category: "Họ Cam Quýt",
    price: 60000,
    stock: 4,
    status: "Sắp hết hàng",
  },
  {
    id: "SP010",
    name: "Sầu Riêng Ri6",
    img: "https://via.placeholder.com/80x80.png?text=Sầu+Riêng",
    category: "Trái cây nhiệt đới",
    price: 220000,
    stock: 0,
    status: "Hết hàng",
  },
  {
    id: "SP011",
    name: "Cherry Mỹ",
    img: "https://via.placeholder.com/80x80.png?text=Cherry",
    category: "Quả Mọng",
    price: 550000,
    stock: 45,
    status: "Còn hàng",
  },
  {
    id: "SP012",
    name: "Dưa Hấu Không Hạt",
    img: "https://via.placeholder.com/80x80.png?text=Dưa+Hấu",
    category: "Trái cây nhiệt đới",
    price: 50000,
    stock: 150,
    status: "Còn hàng",
  },
  {
    id: "SP013",
    name: "Măng Cụt Lái Thiêu",
    img: "https://via.placeholder.com/80x80.png?text=Măng+Cụt",
    category: "Trái cây nhiệt đới",
    price: 120000,
    stock: 0,
    status: "Hết hàng",
  },
  {
    id: "SP014",
    name: "Vải Thiều Bắc Giang",
    img: "https://via.placeholder.com/80x80.png?text=Vải+Thiều",
    category: "Trái cây nhiệt đới",
    price: 85000,
    stock: 5,
    status: "Sắp hết hàng",
  },
];
